### ISSUE TITLE
Toolbox - Establish a build system for all of our C++ projects

### ISSUE THREAD

**Issue by DannyPeck** [CachedNerds/Toolbox#22]
We need to choose a build system to manage the compilation and linking of our projects.  Maintaining a makefile is simply not realistic and is only a short-term solution.  This should be very well thought out as it is something that will be very hard to change in the future.

**Comment by DannyPeck** [comment]
As a part of this issue, we need to also setup a continuous integration system to automatically build projects and execute their tests.

**Comment by xmclark** [comment]
I surveyed a few of the popular build tools. I can't say I'm in love with any of them. All build systems I looked at are cross-platform. They all could easily build using g++ or clang. Some do makefile generation. 

I found this [stackoverflow post](https://stackoverflow.com/questions/12017580/c-build-systems-what-to-use) and picked out a few of the popular ones.

**make:** I actually like make. It's simple. It requires lots of regular maintenance and can become a little unreadable if things scale. I'm not sure how much these little libraries will grow. It may make sense to keep using make for small libraries, since make can be easily called from other build systems.

**CMake:** Clearly the most popular build system besides make. Syntax is odd. Docs are dense, but dense isn't bad. It easily generates make files. It can generate vcxproj files but I'm not sure to what detail or precision. I believe going with CMake would require a bit of learning on our part, but it might be a good long investment.

**qmake:** I have used this before. It is simple, and mostly Qt agnostic (despite its origin). Docs are subpar. It can generate vcxproj files but I don't think there is much precision control of that generation. It does generate make file. This would have the smallest learning curve, and would be good for small projects, but may not scale well (same issues as make). [Tutorial](http://doc.qt.io/qt-5/qmake-tutorial.html).

 **tup:** A newer build system that sells itself on speed. I also really like ML-style syntax and substitution flags. Itself does not generate makefiles or vcxproj files, but makes build process a bit easier, and I think it would scale well. [this](http://gittup.org/tup/ex_a_first_tupfile.html) gives a really great tutorial.

**boost build:** Pro: no need to get another dependency! Con: only builds C++. Syntax looks ok. Tutorial [here](http://www.boost.org/build/tutorial.html).

**bazel:** Written by Google. Can output visualizations. Looks like its setup to easily build other toolchains, and integrates with GOOGLE_TEST. [Tutorial](https://docs.bazel.build/versions/master/tutorial/cpp.html).

I personally like tup the most, but am open to the others. Boost.Build is my second because it appears to integrate with Boost well, but I could see us shooting it down beause it only does C++. CMake would be my ~~second~~ third but I'm hesitant about the learning curve. I prefer we pick a build system that we all feel comfortable working with, rather than one that is popular. I want other people to read my build scripts as easily as they read their own. 

**A few added comments**:
I point out the generation of vcxproj files because I am personally developing on windows. This doesn't mean I will always be developing with the VC++ compiler (in fact I can use the Clang front-end in visual studio), but it does allow me to do development easily in my preferred IDE. If we choose a build system that does not generate vcxproj files, this is not the end of the world, and I will probably write a code generator myself that I may add to the tool box :)

**Comment by technetos** [comment]
1) Tup
2) Make
3) I dont like the others, they add levels of complexity I dont want in a build system.  

Boost Build: I plan to add rust projects in here eventually so boost build is a non-option

**Comment by xmclark** [comment]
How easy can we build rust with tup? Not too familiar with the build system in rust. I

**Comment by DannyPeck** [comment]
No need to use tup at all, Rust uses Cargo to handle all of build related operations.

**Comment by DannyPeck** [comment]
Note, we need to figure out how to setup tup to support projects defining their own subdirectories and still be able to build the source files correctly.

**Comment by technetos** [comment]
I think that task ^ will come down to good documentation

**Comment by technetos** [comment]
https://github.com/CachedNerds/Hatch/issues/6
